name: Java CI

on:
  push:
    branches: [ feature-bhagyesh ]
    tags: "*"
  pull_request:
    branches: [ feature-bhagyesh ]
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [ "event-triggered-by-jira" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Ant
        run: echo "Bhagyesh Daga"
